# Generated by Django 5.0.7 on 2024-07-15 07:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_auto_20240715_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
