# Generated by Django 5.0.7 on 2024-07-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teclado',
            field=models.CharField(default='Mecanico', max_length=250),
        ),
    ]
