# Generated by Django 5.0.7 on 2024-07-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meca', '0002_user_teclado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='teclado',
            new_name='keyboard',
        ),
    ]
